"""add auto_reply_enabled to session

Revision ID: 086daa71973b
Revises: a1f2b3c4d5e6
Create Date: 2026-02-10 01:26:26.520093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '086daa71973b'
down_revision: Union[str, Sequence[str], None] = 'a1f2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_migrations')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.drop_table('store')
    op.alter_column('agent_mcp_server', 'agent_id',
               existing_type=sa.UUID(),
               comment='所属 Agent ID',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='MCP Server 显示名称（如: database-tools, weather-api）',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'description',
               existing_type=sa.TEXT(),
               comment='MCP Server 描述',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'transport',
               existing_type=sa.VARCHAR(length=50),
               comment='传输协议类型 (http/streamable-http, sse, stdio)',
               existing_nullable=False,
               existing_server_default=sa.text("'http'::character varying"))
    op.alter_column('agent_mcp_server', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment='MCP Server URL (如: http://localhost:8000/mcp)',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='自定义 HTTP Headers（如 Authorization）',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用此 MCP Server',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_mcp_server', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序权重',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_mcp_server', 'last_connected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后成功连接时间',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'last_error',
               existing_type=sa.TEXT(),
               comment='最后一次连接错误信息',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'cached_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='缓存的工具列表 [{name, description, input_schema}]',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('agent_mcp_server', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('agent_mcp_server', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_subagent', 'parent_agent_id',
               existing_type=sa.UUID(),
               comment='父 Agent ID',
               existing_nullable=False)
    op.alter_column('agent_subagent', 'child_agent_id',
               existing_type=sa.UUID(),
               comment='子 Agent ID (被挂载的 Agent)',
               existing_nullable=False)
    op.alter_column('agent_subagent', 'mount_description',
               existing_type=sa.TEXT(),
               comment='在父 Agent 上下文中的角色描述，覆盖子 Agent 的通用 description',
               existing_nullable=True)
    op.alter_column('agent_subagent', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='在父 Agent 的 SubAgent 列表中的排序位置',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_subagent', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='挂载时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_agent_subagent_child'), table_name='agent_subagent')
    op.drop_index(op.f('ix_agent_subagent_parent'), table_name='agent_subagent')
    op.alter_column('embedding_config', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='业务类别: message, document 等',
               existing_nullable=False)
    op.alter_column('embedding_config', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               comment='EMBEDDING_MODELS 注册表中的 key',
               existing_nullable=False)
    op.alter_column('embedding_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_embedding', 'search_index_id',
               existing_type=sa.UUID(),
               comment='关联搜索索引记录',
               existing_nullable=False)
    op.alter_column('message_embedding', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               comment='生成此 embedding 的模型ID',
               existing_nullable=False)
    op.alter_column('message_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(),
               comment='halfvec 向量（无维度限制）',
               existing_nullable=False)
    op.alter_column('message_embedding', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: pending/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('message_embedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_msg_embedding_hnsw_bge_m3'), table_name='message_embedding', postgresql_ops={'(embedding::halfvec(1024))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'bge-m3'::text)")
    op.drop_index(op.f('idx_msg_embedding_hnsw_openai_3_large'), table_name='message_embedding', postgresql_ops={'(embedding::halfvec(3072))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'openai-3-large'::text)")
    op.drop_index(op.f('idx_msg_embedding_hnsw_openai_3_small'), table_name='message_embedding', postgresql_ops={'(embedding::halfvec(1536))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'openai-3-small'::text)")
    op.alter_column('message_search_index', 'message_id',
               existing_type=sa.UUID(),
               comment='关联消息ID',
               existing_nullable=False)
    op.alter_column('message_search_index', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户ID（反范式，权限隔离）',
               existing_nullable=False)
    op.alter_column('message_search_index', 'session_id',
               existing_type=sa.UUID(),
               comment='所属会话ID（反范式）',
               existing_nullable=False)
    op.alter_column('message_search_index', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               comment='会话类型快照: pm/group/ai',
               existing_nullable=False)
    op.alter_column('message_search_index', 'session_name',
               existing_type=sa.VARCHAR(length=255),
               comment='会话名称快照',
               existing_nullable=True)
    op.alter_column('message_search_index', 'topic_id',
               existing_type=sa.UUID(),
               comment='话题ID（用于上下文检索）',
               existing_nullable=True)
    op.alter_column('message_search_index', 'sender_name',
               existing_type=sa.VARCHAR(length=255),
               comment='发送者名称快照',
               existing_nullable=True)
    op.alter_column('message_search_index', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='消息角色: user/assistant/system',
               existing_nullable=False)
    op.alter_column('message_search_index', 'message_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='原始消息创建时间',
               existing_nullable=False)
    op.alter_column('message_search_index', 'content_text',
               existing_type=sa.TEXT(),
               comment='拼接后的可搜索文本',
               existing_nullable=False)
    op.alter_column('message_search_index', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='索引写入时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('session', sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False, server_default=sa.false(), comment='是否启用自动回复（仅 pm/group 会话有效）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'auto_reply_enabled')
    op.alter_column('message_search_index', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='索引写入时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_search_index', 'content_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='拼接后的可搜索文本',
               existing_nullable=False)
    op.alter_column('message_search_index', 'message_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='原始消息创建时间',
               existing_nullable=False)
    op.alter_column('message_search_index', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='消息角色: user/assistant/system',
               existing_nullable=False)
    op.alter_column('message_search_index', 'sender_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='发送者名称快照',
               existing_nullable=True)
    op.alter_column('message_search_index', 'topic_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='话题ID（用于上下文检索）',
               existing_nullable=True)
    op.alter_column('message_search_index', 'session_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='会话名称快照',
               existing_nullable=True)
    op.alter_column('message_search_index', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='会话类型快照: pm/group/ai',
               existing_nullable=False)
    op.alter_column('message_search_index', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属会话ID（反范式）',
               existing_nullable=False)
    op.alter_column('message_search_index', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属用户ID（反范式，权限隔离）',
               existing_nullable=False)
    op.alter_column('message_search_index', 'message_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联消息ID',
               existing_nullable=False)
    op.create_index(op.f('idx_msg_embedding_hnsw_openai_3_small'), 'message_embedding', [sa.literal_column('(embedding::halfvec(1536))')], unique=False, postgresql_ops={'(embedding::halfvec(1536))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'openai-3-small'::text)")
    op.create_index(op.f('idx_msg_embedding_hnsw_openai_3_large'), 'message_embedding', [sa.literal_column('(embedding::halfvec(3072))')], unique=False, postgresql_ops={'(embedding::halfvec(3072))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'openai-3-large'::text)")
    op.create_index(op.f('idx_msg_embedding_hnsw_bge_m3'), 'message_embedding', [sa.literal_column('(embedding::halfvec(1024))')], unique=False, postgresql_ops={'(embedding::halfvec(1024))': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where="((model_id)::text = 'bge-m3'::text)")
    op.alter_column('message_embedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_embedding', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: pending/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('message_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.halfvec.HALFVEC(),
               comment=None,
               existing_comment='halfvec 向量（无维度限制）',
               existing_nullable=False)
    op.alter_column('message_embedding', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='生成此 embedding 的模型ID',
               existing_nullable=False)
    op.alter_column('message_embedding', 'search_index_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联搜索索引记录',
               existing_nullable=False)
    op.alter_column('embedding_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('embedding_config', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='EMBEDDING_MODELS 注册表中的 key',
               existing_nullable=False)
    op.alter_column('embedding_config', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='业务类别: message, document 等',
               existing_nullable=False)
    op.create_index(op.f('ix_agent_subagent_parent'), 'agent_subagent', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_subagent_child'), 'agent_subagent', ['child_agent_id'], unique=False)
    op.alter_column('agent_subagent', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='挂载时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_subagent', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在父 Agent 的 SubAgent 列表中的排序位置',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_subagent', 'mount_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='在父 Agent 上下文中的角色描述，覆盖子 Agent 的通用 description',
               existing_nullable=True)
    op.alter_column('agent_subagent', 'child_agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='子 Agent ID (被挂载的 Agent)',
               existing_nullable=False)
    op.alter_column('agent_subagent', 'parent_agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='父 Agent ID',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_mcp_server', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('agent_mcp_server', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('UTC'::text, now())"))
    op.alter_column('agent_mcp_server', 'cached_tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='缓存的工具列表 [{name, description, input_schema}]',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'last_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='最后一次连接错误信息',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'last_connected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后成功连接时间',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序权重',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_mcp_server', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用此 MCP Server',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_mcp_server', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='自定义 HTTP Headers（如 Authorization）',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='MCP Server URL (如: http://localhost:8000/mcp)',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'transport',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='传输协议类型 (http/streamable-http, sse, stdio)',
               existing_nullable=False,
               existing_server_default=sa.text("'http'::character varying"))
    op.alter_column('agent_mcp_server', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='MCP Server 描述',
               existing_nullable=True)
    op.alter_column('agent_mcp_server', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MCP Server 显示名称（如: database-tools, weather-api）',
               existing_nullable=False)
    op.alter_column('agent_mcp_server', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属 Agent ID',
               existing_nullable=False)
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    # ### end Alembic commands ###
