"""add api_key to user table

Revision ID: 0d8e7f9c8696
Revises: 15d32254bb88
Create Date: 2026-01-20 21:47:10.022482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8e7f9c8696'
down_revision: Union[str, Sequence[str], None] = '15d32254bb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
