"""initial revision

Revision ID: 4ea23c627bce
Revises: 
Create Date: 2026-01-12 01:01:26.552541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea23c627bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False, comment='活动类型'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='活动名称'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级，数字越大优先级越高'),
    sa.Column('comments', sa.Text(), nullable=True, comment='备注'),
    sa.Column('tags', sa.ARRAY(sa.String(length=100)), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True, comment='标签列表'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='来源类型，如 manual/event/topic'),
    sa.Column('source_id', sa.String(length=255), nullable=True, comment='来源ID'),
    sa.Column('relation_ids', sa.ARRAY(sa.String(length=255)), server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=True, comment='关联ID列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/active/done/dismissed'),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True, comment='提醒时间'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='截止日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_relation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False, comment='关联的活动ID'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标类型'),
    sa.Column('target_id', sa.String(length=255), nullable=False, comment='目标ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_relation')
    op.drop_table('event')
    op.drop_table('activity')
    # ### end Alembic commands ###
