"""add_session_topic_message_agent_tables

Revision ID: 554b041e94f8
Revises: 4ea23c627bce
Create Date: 2026-01-16 18:02:14.108375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554b041e94f8'
down_revision: Union[str, Sequence[str], None] = '4ea23c627bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent 名称'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_sender',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='发送者名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='会话名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='会话类型: pm/group/ai/<plugin_type>'),
    sa.Column('agent_id', sa.UUID(), nullable=True, comment='关联的 Agent ID'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源: null/astr_wechat/astr_qq/manual_upload'),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True, comment='最后访问时间，用于已读未读'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='话题名称'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='所属会话ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='所属会话ID'),
    sa.Column('topic_id', sa.UUID(), nullable=True, comment='所属话题ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('sender_id', sa.UUID(), nullable=True, comment='发送者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['sender_id'], ['message_sender.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_part',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='所属消息ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='内容类型: text/plain/image/url/json'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容: string/jsonstr/base64/url'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('event_id', sa.String(length=255), nullable=True, comment='关联事件ID'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_part')
    op.drop_table('message')
    op.drop_table('topic')
    op.drop_table('session')
    op.drop_table('message_sender')
    op.drop_table('agent')
    # ### end Alembic commands ###
