"""add_deepagents_schema

Revision ID: 62ce0e232e8b
Revises: 316ad3135171
Create Date: 2026-01-26 22:26:28.019487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62ce0e232e8b'
down_revision: Union[str, Sequence[str], None] = '316ad3135171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get connection and default user for NULL updates
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id FROM \"user\" LIMIT 1"))
    first_user = result.fetchone()
    default_user_id = first_user[0] if first_user else None
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号，从 1 开始递增'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent 名称快照'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词快照'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='模型名称快照'),
    sa.Column('model_provider', sa.String(length=50), nullable=True, comment='模型提供商快照'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度参数快照'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大 token 数快照'),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具列表快照'),
    sa.Column('subagents_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SubAgents 配置快照'),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据快照'),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='变更摘要'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_version')
    )
    op.create_table('subagent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_agent_id', sa.UUID(), nullable=False, comment='父 Agent ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='子代理名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='子代理描述，用于任务委派时的选择'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='子代理系统提示词'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='子代理使用的模型，为空则继承父 Agent'),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='子代理可用工具列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Update NULL user_id values in activity
    if default_user_id:
        conn.execute(
            sa.text("UPDATE activity SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": default_user_id}
        )
    
    op.alter_column('activity', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属用户ID')
    op.alter_column('activity', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.add_column('agent', sa.Column('model', sa.String(length=100), nullable=True, comment='模型名称'))
    op.add_column('agent', sa.Column('model_provider', sa.String(length=50), nullable=True, comment='模型提供商'))
    op.add_column('agent', sa.Column('temperature', sa.Float(), nullable=True, comment='温度参数'))
    op.add_column('agent', sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大 token 数'))
    op.add_column('agent', sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具列表'))
    # Update NULL user_id values in event
    if default_user_id:
        conn.execute(
            sa.text("UPDATE event SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": default_user_id}
        )
    
    op.alter_column('event', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属用户ID')
    # Update NULL user_id values in message
    if default_user_id:
        conn.execute(
            sa.text("UPDATE message SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": default_user_id}
        )
    
    op.alter_column('message', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属用户ID')
    op.alter_column('message', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('message', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='角色: user/assistant/system/self/null',
               existing_comment='角色: user/assistant/system',
               existing_nullable=False)
    op.alter_column('message_part', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='内容类型: text/image/at/url/json',
               existing_comment='内容类型: text/plain/image/url/json',
               existing_nullable=False)
    # Update NULL user_id values in session
    if default_user_id:
        conn.execute(
            sa.text("UPDATE session SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": default_user_id}
        )
    
    op.alter_column('session', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属用户ID')
    op.alter_column('session', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # Update NULL user_id values in topic
    if default_user_id:
        conn.execute(
            sa.text("UPDATE topic SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": default_user_id}
        )
    
    op.alter_column('topic', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属用户ID')
    op.alter_column('topic', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('topic', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='所属用户ID')
    op.alter_column('session', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('session', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='所属用户ID')
    op.alter_column('message_part', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='内容类型: text/plain/image/url/json',
               existing_comment='内容类型: text/image/at/url/json',
               existing_nullable=False)
    op.alter_column('message', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='角色: user/assistant/system',
               existing_comment='角色: user/assistant/system/self/null',
               existing_nullable=False)
    op.alter_column('message', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('message', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='所属用户ID')
    op.alter_column('event', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='所属用户ID')
    op.drop_column('agent', 'tools')
    op.drop_column('agent', 'max_tokens')
    op.drop_column('agent', 'temperature')
    op.drop_column('agent', 'model_provider')
    op.drop_column('agent', 'model')
    op.alter_column('activity', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号，每次更新递增',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('activity', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='所属用户ID')
    op.drop_table('subagent')
    op.drop_table('agent_version')
    # ### end Alembic commands ###
