import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  paragraph: 'mb-1 leading-7',
  heading: {
    h1: 'text-3xl font-bold mt-6 mb-3',
    h2: 'text-2xl font-bold mt-5 mb-2',
    h3: 'text-xl font-semibold mt-4 mb-2',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline underline-offset-2',
    strikethrough: 'line-through',
    code: 'rounded-md bg-muted px-1.5 py-0.5 font-mono text-sm',
  },
  list: {
    ul: 'list-disc list-outside ml-4 my-2',
    ol: 'list-decimal list-outside ml-4 my-2',
    listitem: 'leading-normal my-1',
    nested: { listitem: 'list-none' },
    listitemChecked:
      'lexical-listitem-checked line-through text-muted-foreground relative pl-6 list-none',
    listitemUnchecked:
      'lexical-listitem-unchecked relative pl-6 list-none',
    olDepth: [
      'list-decimal',
      'list-[lower-alpha]',
      'list-[lower-roman]',
    ],
    ulDepth: ['list-disc', 'list-circle', 'list-square'],
  },
  quote:
    'border-l-4 border-primary pl-4 italic my-4 text-muted-foreground',
  link: 'text-primary underline underline-offset-[3px] hover:text-primary/80 transition-colors cursor-pointer',
  code: 'not-prose rounded-md bg-muted border p-4 font-mono text-sm block my-4 overflow-x-auto',
  codeHighlight: {
    atrule: 'text-[#e45649] dark:text-[#ff7b72]',
    attr: 'text-[#986801] dark:text-[#ffa657]',
    boolean: 'text-[#0184bb] dark:text-[#79c0ff]',
    builtin: 'text-[#e45649] dark:text-[#ffa657]',
    cdata: 'text-[#a0a1a7] dark:text-[#8b949e]',
    char: 'text-[#50a14f] dark:text-[#a5d6ff]',
    class: 'text-[#c18401] dark:text-[#ffa657]',
    'class-name': 'text-[#c18401] dark:text-[#ffa657]',
    comment: 'text-[#a0a1a7] dark:text-[#8b949e]',
    constant: 'text-[#986801] dark:text-[#79c0ff]',
    deleted: 'text-[#e45649] dark:text-[#ffdcd7]',
    doctype: 'text-[#a0a1a7] dark:text-[#8b949e]',
    entity: 'text-[#986801] dark:text-[#ffa657]',
    function: 'text-[#4078f2] dark:text-[#d2a8ff]',
    important: 'text-[#c18401] dark:text-[#ffa657]',
    inserted: 'text-[#50a14f] dark:text-[#aff5b4]',
    keyword: 'text-[#a626a4] dark:text-[#ff7b72]',
    namespace: 'text-[#e45649] dark:text-[#ff7b72]',
    number: 'text-[#986801] dark:text-[#79c0ff]',
    operator: 'text-[#a0a1a7] dark:text-[#79c0ff]',
    prolog: 'text-[#a0a1a7] dark:text-[#8b949e]',
    property: 'text-[#4078f2] dark:text-[#79c0ff]',
    punctuation: 'text-[#a0a1a7] dark:text-[#c9d1d9]',
    regex: 'text-[#986801] dark:text-[#a5d6ff]',
    selector: 'text-[#50a14f] dark:text-[#7ee787]',
    string: 'text-[#50a14f] dark:text-[#a5d6ff]',
    symbol: 'text-[#986801] dark:text-[#f2cc60]',
    tag: 'text-[#e45649] dark:text-[#7ee787]',
    url: 'text-[#4078f2] dark:text-[#79c0ff]',
    variable: 'text-[#e45649] dark:text-[#ff7b72]',
  },
  image: 'rounded-lg border border-border max-w-full h-auto cursor-pointer',
  table: 'border-collapse border border-border w-full my-4',
  tableCell: 'border border-border p-2 min-w-[75px] align-top relative',
  tableCellHeader:
    'border border-border p-2 min-w-[75px] bg-muted font-bold align-top relative',
  tableRowStriping: 'even:bg-muted/30',
  horizontalRule: 'my-6 border-t border-muted-foreground/30',
  // Custom node classes
  callout: 'rounded-md p-4 my-3 flex gap-3',
  calloutTypes: {
    info: 'border-l-4 border-blue-500 bg-blue-50 dark:bg-blue-950/30',
    warning: 'border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-950/30',
    error: 'border-l-4 border-red-500 bg-red-50 dark:bg-red-950/30',
    success: 'border-l-4 border-green-500 bg-green-50 dark:bg-green-950/30',
    note: 'border-l-4 border-gray-500 bg-gray-50 dark:bg-gray-950/30',
  },
};
